name: Release

on:
  push:
    branches:
      - main

jobs:
  test-check-lint:
    uses: ./.github/workflows/test-check-lint.yml

  release:
    name: Build Publish Library - Linux-x86_64
    runs-on: public-blitzar-T4-gpu-vm
    timeout-minutes: 600
    needs: [test-check-lint]
    environment: deploy #!! DO NOT CHANGE THIS LINE !! #
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - run: git config --global --add safe.directory $(realpath .)

      - name: Semantic release
        run: |
          nix develop --command npm install semantic-release
          TEST_TMPDIR=$HOME/.bazel_test_opt nix develop --command npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
